# Site Configuration for Dr. Muhammad Munsif's Academic Website

# Site Settings
title: "Dr. Muhammad Munsif"
email: munsif3797@gmail.com
description: >-
  PhD in Computer Science | Researcher in Computer Vision, Deep Learning, VR/AR, 
  Intelligent Transportation Systems | Currently at Intelligent Media Laboratory, Seoul, South Korea
baseurl: ""
url: "https://munsif200.github.io"
twitter_username: ""
github_username: munsif200

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Minimal Mistakes theme configuration
remote_theme: "mmistakes/minimal-mistakes"

# Site Author
author:
  name: "Dr. Muhammad Munsif"
  avatar: "/assets/images/profile.jpg"
  bio: "PhD in Computer Science | Researcher in Computer Vision, Deep Learning, VR/AR, Intelligent Transportation Systems"
  location: "Seoul, South Korea"
  email: "munsif3797@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/munsif200"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/munsif200"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:munsif3797@gmail.com"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Custom CSS
after_footer_scripts:
  - /assets/css/custom.css

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Asia/Seoul

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# SEO
locale: "en-US"
title_separator: "-"
name: "Dr. Muhammad Munsif"